server:
  port: 9001
spring:
  application:
    name: service-order
  config:
    import:
      - nacos:boot-common.yml?group=DEFAULT_GROUP&refreshEnabled=true
      - nacos:service-order.yml?group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        namespace: boot-cli
      discovery:
        namespace: boot-cli
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order_db
    username: sa
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

