server:
  port: 9000
spring:
  application:
    name: service-ai
  mvc:
    servlet:
      path: /ai
  ai:
    model:
      chat: none
      image: none
      embedding: none
      moderation: none
      audio:
        transcription: none
        speech: none

cli:
  ai:
    model:
      openai:
        services:
          doubao:
            base-url: https://ark.cn-beijing.volces.com/api/v3
            completions-path: /chat/completions
            simple-api-key: 4cdb****
      google:
        api-key: A****
        file-search-store-display-name: FSS_SERVICE_AI